### ISSUE TITLE
Marketplace Image Support

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [ManageIQ/azure-armrest#288]
As talked about [here](http://talk.manageiq.org/t/deploying-azure-marketplace-images/2521) I'm opening an RFE for marketplace image support. From what I can see this will require:
* Altering ```prepare_for_clone_task``` to parse and accept marketplace URNs
* Adding a method to pull marketplace images to the refresh parser
* Maybe adding something akin to the public image settings and filter found in [the Amazon provider](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/config/settings.yml)?

**Comment by djberg96** [comment]
We can close this issue here, you've still got the other one open, and I've already merged the update to VirtualMachineImageService. I'm just waiting on one other PR to be merged, then I'll release an updated azure-armrest gem.

Note that you'll need to update your PR to use the latest azure-armrest gem once it's released.
