### ISSUE TITLE
ClassicCompute does not have network interfaces

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#44]
It seems there is no networkInterfaces property for classic VM's:
```
vmm.provider = "Microsoft.ClassicCompute"
vmm.list

# Output
/Users/dberger/Repositories/azure-armrest/lib/azure/armrest/virtual_machine_manager.rb:132:in `block in add_network_profile': undefined method `each' for nil:NilClass (NoMethodError)
```

**Comment by bronaghs** [comment]
@djberg96
If there is an overhead to supporting ClassicCompute I am not sure we should support it, the requirements were to support "Compute", "ClassicCompute" seemed to be a bonus we were offering. Thoughts?

@blomquisg 
Microsoft were pretty specific about supporting the newer 'Compute' namespace, since we already started with the ClassicCompute namespace we just began to support both. I now realize there is a big difference between the two, any reason why we should not drop support for 'ClassicCompute'?

**Comment by blomquisg** [comment]
@bronaghs, @djberg96:  if the ClassicCompute support in the API starts taking time away from supporting Compute, then stop on the ClassicCompute front.

If needed, you can always circle back and add support later.

**Comment by djberg96** [comment]
@blomquisg Understood, we'll focus just on Compute.

**Comment by djberg96** [comment]
We decided to just skip gathering the extra information for any provider other than Microsoft.Compute.
